[WIP] Activity tracking for admin
codeuino/social-platform-donut-backend pull request #150
Opened 2020-07-14 16:47 UTC by kmehant

Signed-off-by: K mehant <411843@student.nitandhra.ac.in>
[Work in progress]
partially closes #148

2020-07-15 10:25 UTC, Rupeshiya requested changes
@kmehant We should not only record the timestamp and routes but what we want is basically the activity of the user let say a user "X" is creating a post so what he will do:
1. Send POST request to /post
2. With some data
So it should store the activity like: userId, postId, timeStamp, so that we when we render in the client side then from there on clicking a particular activity an admin can navigate to that post.

Also, we should not call the middleware on GET requests as we are not interested in what the user is exploring on the platform but we are interested in what actions he/she is performing on the platform.

2020-07-15 11:40 UTC, kmehant commented
> @kmehant We should not only record the timestamp and routes but what we want is basically the activity of the user let say a user "X" is creating a post so what he will do:
> 
> 1. Send POST request to /post
> 2. With some data
>    So it should store the activity like: userId, postId, timeStamp, so that we when we render in the client side then from there on clicking a particular activity an admin can navigate to that post.
> 
> Also, we should not call the middleware on GET requests as we are not interested in what the user is exploring on the platform but we are interested in what actions he/she is performing on the platform.

@Rupeshiya 
Thank you for the review
I had this doubt, I guess I spoke about the data model in the issue for your approval 🥺☹️ before implementing it. 
For get requests thing, I haven't used the middleware yet, we can include this middleware to any route we wish to use. 

@Rupeshiya @vaibhavdaren @devesh-verma 
Please 🙏🙏 I guess it would be easy if we can discuss on the design, approach correctly and the outcomes so that we all will be on the same page ✌️ and intention.

2020-07-15 15:04 UTC, Rupeshiya commented on app/middleware/activity.js
> +      'tokens.token': token
use user-id instead of the token as by default indexing is done on _id in mongoose so it would give better performance.

2020-07-15 16:32 UTC, vaibhavdaren commented
HASH   ---> (KEY, HASH_VALUE)
						|				 
(USER)       |         (RANDOM)
		   (ROUTE)
		      |
		IS THIS UNIQUE?

			KEY           HASH		 ID_OF_OBJECT_RETURNED
 HASH  ---> TIME STAMP ---> ROUTE -->      (UUID_mogo_id)
    |
(per_user)

2020-07-16 13:04 UTC, Rupeshiya reviewed
@kmehant Awesome!!
Also I think we need to add this middleware in every routes except GET requests. In addition to that do you think we need to track user login and logout??

Also will it work in case of comment, because in that case we want postId as well as commentId??

2020-07-16 13:04 UTC, Rupeshiya commented on app/middleware/activity.js
> +      data.activity.push(activityElement)
change push to unshift, we want recent activity as first element.

2020-07-18 06:27 UTC, Rupeshiya commented
@kmehant Also please add the API to fetch those user activity data from DB.

2020-07-18 07:22 UTC, kmehant commented
> Also will it work in case of comment, because in that case we want postId as well as commentId??

@Rupeshiya Yes, it should work! 
based on the response as I can see `postid` and `commentid` keys in the response object already. So we can use them.

2020-07-18 07:27 UTC, kmehant commented on app/middleware/activity.js
> +  } else if (method != 'GET') {
> @kmehant Awesome!!
> Also I think we need to add this middleware in every routes except GET requests. In addition to that do you think we need to track user login and logout??

@Rupeshiya I have written check condition here so we can add it everywhere safely 😁

2020-07-18 07:28 UTC, kmehant reviewed
@Rupeshiya

2020-07-18 07:36 UTC, kmehant commented
@Rupeshiya Can you suggest API endpoints so that I can move forward

2020-07-18 15:10 UTC, Rupeshiya commented
> @Rupeshiya Can you suggest API endpoints so that I can move forward

Yeah, let it be /user/:id/activity (here id is the userId as we want to fetch for each user by their id)

2020-08-13 14:27 UTC, vaibhavdaren commented
@kmehant ETA?

2025-06-10 17:49 UTC, closed without merging