add docs for new contributors
codeuino/social-platform-donut-backend pull request #181
Opened 2020-08-26 20:26 UTC by Rupeshiya

---
name: Pull Request template
about: Describe the PR.
title: ''
labels: ''
assignees: ''

---

### **Problem**
Github Issue Number: #179 
Improve docs for new contributors

### **Solution of problem**
Add the links of the docs for reference and describe the workflow to follow to use the platform

### **Type of Change**
[ ] Bug fix
[ ] New Feature
[ ] Development of UI/UX prototypes
[ ] Small refactor
[&check;] Change in Documentation

### **Checklist**
[&check;] My code follows the same style as the codebase
[&check;] My Code change requires a change in documentation
[&check;] I have updated the Readme accordingly
[&check;] I made PR against **development branch**
[&check;] I have run the test cases locally and it's passing.
[&check;] I have squashed my commits

2020-08-27 09:32 UTC, Rupeshiya commented
@vaibhavdaren Plz review

2020-08-27 11:12 UTC, ksraj123 requested changes
Some humble suggestions that may help in improving the experience of new contributors.

Please see my comments.

2020-08-27 11:25 UTC, Rupeshiya commented on README.md
> +        <td><code>Too many requests</code></td>
@ksraj123 Please check this https://github.com/codeuino/social-platform-donut-backend/pull/178

2020-08-27 11:26 UTC, Rupeshiya commented on README.md
> +Please follow the steps provided in the documentation to setup locally: [Documentation](https://docs.codeuino.org/donut-social-networking-platform/installations/pre-requisite)
@jaskiratsingh2000 Should I write that here too?

2020-08-27 11:26 UTC, Rupeshiya commented on README.md
> +NOTE: Make sure you have installed the pre-requisite and setup the environment variables in **.env.dev** (for development) and **.env.test** (for unit test) provided in the documentation.
@jaskiratsingh2000 Should I write that here too in Readme?

2020-08-27 11:36 UTC, jaskiratsingh2000 commented
Sure, go ahead

On Thu, Aug 27, 2020 at 4:26 AM Rupesh Krishna Jha <notifications@github.com>
wrote:

> *@Rupeshiya* commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/codeuino/social-platform-donut-backend/pull/181#discussion_r478345276>
> :
>
> >
> -- bcrypt :- hash your plain password and store hashed password in database.
> -- body-parser :- Parse incoming request bodies in a middleware before your handlers, available under the req.bodyproperty.
> -- express :- Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.
> -- jsonwebtoken :- JSON Web Token (JWT) is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object.
> -- mongoose :- Mongoose is a MongoDB object modeling tool designed to work in an asynchronous environment.
> -- morgan :- HTTP request logger middleware for node.js.
> -- nodemon :- nodemon will watch the files in the directory in which nodemon was started, and if any files change, nodemon will automatically restart your node application.
> +NOTE: Make sure you have installed the pre-requisite and setup the environment variables in **.env.dev** (for development) and **.env.test** (for unit test) provided in the documentation.
>
> @jaskiratsingh2000 <https://github.com/jaskiratsingh2000> Should I write
> that here too in Readme?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codeuino/social-platform-donut-backend/pull/181#discussion_r478345276>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOBHK2NBOQTRYN3YNSASR3SCY7IHANCNFSM4QMHGP5Q>
> .
>

2020-08-27 11:54 UTC, ayushnagar123 approved these changes
Please make the required changes as suggested  by saurabh rest looks good to me

2020-08-27 12:20 UTC, Rupeshiya commented
@ayushnagar123 @jaskiratsingh2000 @ksraj123 @vaibhavdaren @AuraOfDivinity Please review again

2020-08-27 12:34 UTC, ksraj123 approved these changes

2020-08-27 12:37 UTC, AuraOfDivinity approved these changes

2020-08-27 12:39 UTC, ayushnagar123 approved these changes

2020-08-31 06:43 UTC, Rupeshiya commented
@vaibhavdaren Please review

2020-08-31 22:21 UTC, merged